wire auth and solvers service, auth docker image change, timeout change
YousofMersal/DM885_Project_DevSecOps pull request #42
Opened 2022-12-11 17:03 UTC by jonasgroendahl

2022-12-11 17:10 UTC, YousofMersal requested changes

2022-12-11 17:10 UTC, YousofMersal commented on services/auth/Dockerfile
> +ENTRYPOINT [ "dm885_auth_service" ]
Hmm, jeg ved ikke om det er en god idé at includere denne docker fil, jeg ved ikke om den bygger imaget på en måde som vil virke i vores pipeline. Så den vil muligvis ødelægge auth i pipelinen. 

Jeg er dog ikke 100%

2022-12-11 17:25 UTC, YousofMersal approved these changes

2022-12-11 21:09 UTC, YousofMersal commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
man kan sætte et environment variable med  inde i service.yml kunne man sætte den for pod'en således

```
env:
    - name: HOST
      value: "{{.Values.publicDomain}}"
```
Så vil helm erstatte med det faktisk domæne når det bliver spun-up selvom der står example domain.

og så kan man bare læse HOST environmnt variablet (eller whatever andet man nu har set  som env for det)

2022-12-12 11:45 UTC, viktorstrate commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
Istio VirtualRoutes burde gøre sådan at alle services kan tilgås fra `project.127.0.0.1.sslip.io` (`PUBLIC_DOMAIN`) domænet.
Altså vil `project.127.0.0.1.sslip.io/api/v1` automatisk viderestilles til `auth-service.project.127.0.0.1.sslip.io/api/v1` og ligeledes for de andre endpoints.

Hvis vi bruger dette i stedet så tror jeg heller ikke CORS er et problem, og så kan frontend jo bare bruge `location.origin` til at få URL'en til API'et altså `const apiServiceUrl = location.origin + '/api/v1/auth'`.

2022-12-12 12:00 UTC, YousofMersal commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
> Istio VirtualRoutes burde gøre sådan at alle services kan tilgås fra `project.127.0.0.1.sslip.io` (`PUBLIC_DOMAIN`) domænet. Altså vil `project.127.0.0.1.sslip.io/api/v1/auth` automatisk viderestilles til `auth-service.project.127.0.0.1.sslip.io/api/v1/auth` og ligeledes for de andre endpoints.
> 
> Hvis vi bruger dette i stedet så tror jeg heller ikke CORS er et problem, og så kan frontend jo bare bruge `location.origin` til at få URL'en til API'et altså `const apiServiceUrl = location.origin + '/api/v1/auth'`.


Den sætter det i hvert fald ikke til `project.127.0.0.1.sslip.io ` per automatik. 
![image](https://user-images.githubusercontent.com/29578565/207039687-e37d197a-a0d2-44e1-8297-da2780bf72f0.png)

2022-12-12 12:13 UTC, viktorstrate commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
@YousofMersal For local development er `PUBLIC_DOMAIN` og `PROJECT_DOMAIN` det samme. Men kun `PUBLIC_DOMAIN` sættes automatisk af Skaffold. Kan du ikke tilgå `project.YOUR_IP.sslip.io` når frontend services køre?

2022-12-12 12:35 UTC, YousofMersal commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
PUBLIC_DOMAIN er ikke set inde af skaffold i lokal development for mig.

> Kan du ikke tilgå project.YOUR_IP.sslip.io når frontend servicen køre?
Hvad mener du med `YOUR_IP` ?

2022-12-12 14:17 UTC, viktorstrate commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
Her bliver de sat i `skaffold.yaml` for local development.
https://github.com/YousofMersal/DM885_Project_DevSecOps/blob/0e2e68f3ffc348b354b615a09dd7fba131c6b470/services/auth/skaffold.yaml#L17-L19

> Hvad mener du med YOUR_IP?

Den IP som bliver indsat foran `sslip.io`. IP'en på din cluster's external loadbalancer. Den som sættes for `PROJECT_DOMAIN`. På min computer er det `127.0.0.1` men der er anderledes på linux ikke?

2022-12-12 14:32 UTC, YousofMersal commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
> men der er anderledes på linux ikke

Det er basically random hvilken IP det er, den er ikke en fast ip. Hver gang man starter minikube så er det en nu IP.

2022-12-12 14:33 UTC, viktorstrate commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
Ja, det er den IP jeg mener med `YOUR_IP`

2022-12-12 14:39 UTC, YousofMersal commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
Okay, så vil det da betyde at dette ikke er korrekt ikke også?


> Istio VirtualRoutes burde gøre sådan at alle services kan tilgås fra project.127.0.0.1.sslip.io (PUBLIC_DOMAIN) domænet.
Altså vil project.127.0.0.1.sslip.io/api/v1/auth automatisk viderestilles til auth-service.project.127.0.0.1.sslip.io/api/v1/auth og ligeledes for de andre endpoints.

Med mindre du mente at det kan tilgås fra _whatever PUBLIC\_DOMAIN er_ ikke nødvendigvis  `127.0.0.1.sslip.io`, som er min pointe med det originale så det bliver sat til havd det er og ikke hardcoded. 

```
// helm/templates/service.yml
 # snip
env:
    - name: HOST
      value: "{{.Values.publicDomain}}"
 # snip
```

Da `127.0.0.1.sslip.io`  ikke bliver resolvet hos mig nu hvor det er en anden IP

2022-12-12 14:41 UTC, viktorstrate commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
Jeg mener ikke `127.0.0.1`det var bare et eksempel. Det er værdien af `PUBLIC_DOMAIN`.

2022-12-12 14:51 UTC, YousofMersal commented on services/frontend/src/request.ts
> +  "http://solvers-service.project.127.0.0.1.sslip.io/api/v1";
> Jeg mener ikke `127.0.0.1`det var bare et eksempel. Det er værdien af `PUBLIC_DOMAIN`.

Okay, kan jeg så spørge hvor du vil hen med?:

> Istio VirtualRoutes burde gøre sådan at alle services kan tilgås fra `project.127.0.0.1.sslip.io` (`PUBLIC_DOMAIN`) domænet. Altså vil `project.127.0.0.1.sslip.io/api/v1/auth` automatisk viderestilles til `auth-service.project.127.0.0.1.sslip.io/api/v1/auth` og ligeledes for de andre endpoints.
> 
> Hvis vi bruger dette i stedet så tror jeg heller ikke CORS er et problem, og så kan frontend jo bare bruge `location.origin` til at få URL'en til API'et altså `const apiServiceUrl = location.origin + '/api/v1/auth'`.

Som jeg forstå hvad du skriver vil du bruge `PUBLIC_DOMAIN` inde i servicen? Eller hvad er din pointe?

2022-12-13 14:55 UTC, merged